### PR TITLE
Use a voice detector instead of noise floor

### PR DESCRIPTION
**Pull request by virtuallyaverage**
I implemented a janky solution to help with getting user requests in a noisy environment. The requirement is already on the venv list, so I just updated the function and replaced the current function, along with a few variables to support the functionality. Merge or modify, I don't know what would be best.

It does help a lot when stuff is playing on speakers though. so I am going to continue using it.

### CODE REVIEW

**Review by virtuallyaverage — COMMENTED** [review]
something someting

**Review by gianmarcoguarnier — APPROVED** [review]

**Comment by gianmarcoguarnier** [comment]
@virtuallyaverage are you having the same problem with ```speaked```? I am being silent but the voice is detected in the first audi frames (probably because it reads the 'jarvis' segment.
Capture

I was trying to tell the vad to read data only from when it enters the while loop, did you look into that?

**Comment by virtuallyaverage** [comment]
I have this:
image
you may try setting the aggressiveness down from 3 to two. Your microphone may be different

**Comment by virtuallyaverage** [comment]
then it trails quickly off into the cutoff. Overall this output took about 4 seconds

**Comment by virtuallyaverage** [comment]
Nevermind, I see what you mean. I'm working on it

**Comment by virtuallyaverage** [comment]
image
Add a slight delay before starting recording and it works. The delay is not noticeable, and it does not register the wakeword as speech.

**Comment by gianmarcoguarnier** [comment]
Yeah I investigated a bit on the technical aspects to fix the problem properly but a if/else with a delay of .5 seconds is working fine

**Pull request merged**
